In [3]:
##importing the dataset
import pandas as pd
data=pd.read_csv(r"C:\Users\USER\Downloads\archive (11)\diabetes_prediction_dataset.csv")
data

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [4]:
##checking for missing values
data.isna().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [10]:
##converting categorical columns to numeric
data['gender']=data['gender'].astype('category')
data['gender']=data['gender'].cat.codes
data['smoking_history']=data['smoking_history'].astype('category')
data['smoking_history']=data['smoking_history'].cat.codes
data

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,4,25.19,6.6,140,0
1,0,54.0,0,0,0,27.32,6.6,80,0
2,1,28.0,0,0,4,27.32,5.7,158,0
3,0,36.0,0,0,1,23.45,5.0,155,0
4,1,76.0,1,1,1,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,0,80.0,0,0,0,27.32,6.2,90,0
99996,0,2.0,0,0,0,17.37,6.5,100,0
99997,1,66.0,0,0,3,27.83,5.7,155,0
99998,0,24.0,0,0,4,35.42,4.0,100,0
99999,0,57.0,0,0,1,22.43,6.6,90,0

In [14]:
##selecting the input
input=data.drop('diabetes',axis=1)
input

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,0,80.0,0,1,4,25.19,6.6,140
1,0,54.0,0,0,0,27.32,6.6,80
2,1,28.0,0,0,4,27.32,5.7,158
3,0,36.0,0,0,1,23.45,5.0,155
4,1,76.0,1,1,1,20.14,4.8,155
...,...,...,...,...,...,...,...,...
99995,0,80.0,0,0,0,27.32,6.2,90
99996,0,2.0,0,0,0,17.37,6.5,100
99997,1,66.0,0,0,3,27.83,5.7,155
99998,0,24.0,0,0,4,35.42,4.0,100
99999,0,57.0,0,0,1,22.43,6.6,90

In [16]:
target=data['diabetes']
target

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

In [20]:
##splitting data into 70% training and 30% testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input,target,test_size=0.3,random_state=1)

In [19]:
##decision tree 
from sklearn import tree
model=tree.DecisionTreeClassifier(criterion='entropy',max_depth=3)

In [23]:
model=model.fit(x_train,y_train)
model

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [54]:
##testing accuracy of the model using training data
model.score(x_train,y_train)

0.9717714285714286

In [45]:
##testing the model
test_prediction=model.predict(x_test)
test_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [52]:
## testing the accuracy of the model using test data
model.score(x_test,y_test)

0.9721

In [ ]:
##model has 97.18% accuracy